debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf-8&useSSL=false
    username: fanroot
    password: fanRoot
    driver-class-name: com.mysql.jdbc.Driver